//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatteryMotorMonitor.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatteryTable
    {
        public System.DateTime DateStamp { get; set; }
        public decimal BatteryTemperature { get; set; }
        public decimal BatteryCurrent { get; set; }
        public decimal BatteryVoltage { get; set; }
        public decimal BatteryPower { get; set; }
    }
}
